apiVersion: v1
kind: Secret
metadata:
  name: memorialbooklet-secret
type: Opaque
stringData:
  MYSQL_ROOT_PASSWORD: "replace-me"
  MYSQL_APP_PASSWORD: "replace-me"
  CONFLUX_PRIVATE_KEY: "replace-me"
  CONFLUX_CONTRACT_ADDRESS: "replace-me"

