spring.application.name=Memorial Booklet

# ----------------------------------------------------
# 1. Conflux & IPFS ??
# ----------------------------------------------------
conflux.rpc.url=https://evmtestnet.confluxrpc.com
conflux.private.key=0d53db7f457125bb042e56d3f616044b75609398be1635f6fbf1ff0c18532432
conflux.contract.address=0x2DBF48f90730a16695101e6D270Dd77651682047

# IPFS ??? Multiaddr (?? IPFS ?????)
ipfs.multi.address=/ip4/127.0.0.1/tcp/5001
spring.docker.compose.docker-command=/opt/homebrew/bin/docker

# ----------------------------------------------------
# 2. ???/Docker ??
# ----------------------------------------------------
# ?? Spring Boot Docker Compose ????
spring.docker.compose.enabled=false

# ?? Modulith MongoDB ????????? JPA/Mongo ??
spring.modulith.events.mongodb.transaction-management.enabled=false
spring.devtools.restart.enabled=false

# ----------------------------------------------------
# 3. ?????????? (?? JPA/Cassandra ??)
# ----------------------------------------------------
# ???? JDBC/JPA ????
spring.autoconfigure.exclude[0]=org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
spring.autoconfigure.exclude[1]=org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration
spring.autoconfigure.exclude[2]=org.springframework.boot.autoconfigure.data.jpa.JpaRepositoriesAutoConfiguration

# ?? Modulith ?? JPA/JDBC ?????
spring.autoconfigure.exclude[3]=org.springframework.modulith.events.jpa.JpaEventPublicationAutoConfiguration
spring.autoconfigure.exclude[4]=org.springframework.modulith.events.jdbc.JdbcEventPublicationAutoConfiguration

# ? ????? Cassandra ???? (??????)
spring.autoconfigure.exclude[5]=org.springframework.boot.autoconfigure.cassandra.CassandraAutoConfiguration
spring.autoconfigure.exclude[6]=org.springframework.boot.autoconfigure.data.cassandra.CassandraDataAutoConfiguration
spring.autoconfigure.exclude[7]=org.springframework.boot.autoconfigure.data.cassandra.CassandraRepositoriesAutoConfiguration
spring.autoconfigure.exclude[8]=org.springframework.boot.autoconfigure.data.cassandra.CassandraReactiveDataAutoConfiguration
spring.autoconfigure.exclude[9]=org.springframework.boot.autoconfigure.data.cassandra.CassandraReactiveRepositoriesAutoConfiguration

# ???????? Spring Data Redis?????????
# spring.autoconfigure.exclude[10]=org.springframework.boot.autoconfigure.data.redis.RedisAutoConfiguration
# spring.autoconfigure.exclude[11]=org.springframework.boot.autoconfigure.data.redis.RedisReactiveAutoConfiguration


